version: "2"
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root!1234
      MYSQL_DATABASE: ecommerce_api
      MYSQL_USER: root
    volumes:
      - ./api/services/volumes/data:/var/lib/mysql
  
  api:
    container_name: node-container
    restart: always
    build:
      "./api"
    volumes:
      - ./api:/home/node/app
    environment:
      - MYSQL_URI=mysqldb
    ports:
      - "2000:2000"
    links:
      - "mysqldb:database" 
    depends_on:
      - mysqldb  